### ISSUE TITLE
Extracted section target isn't quite right

### ISSUE THREAD

**Issue by eagr** [awslabs/duvet#66]
Try running

```
duvet extract https://www.rfc-editor.org/rfc/rfc9114.html
```

From the generated toml file:

<img width="443" alt="image" src="https://user-images.githubusercontent.com/64203473/185775585-7da5e8d3-06c3-478e-9b9f-4f84bc802b17.png">

But the link won't navigate to the desired section. The expected target would be

```
target = "https://www.rfc-editor.org/rfc/rfc9114.html#section-3.1.1"
```

It seems like changing the `write_toml` function would be a quick fix for this particular case, but not sure if it's the right move to accommodate all use cases.

**Comment by camshaft** [comment]
Yeah it would be good to use the canonical anchor
