### ISSUE TITLE
Target of copied annotation isn't quite right

### ISSUE THREAD

**Issue by eagr** [awslabs/duvet#67]
The target of an annotation I copied from the generated report was somewhat broken. The target I got was

```
//= https://www.rfc-editor.org/rfc/rfc9114#3.3
```

But the desired one would be

```
//= https://www.rfc-editor.org/rfc/rfc9114#section-3.3
```

Similar to #66 but probably a different problem. I was following the instructions from `duvet help report` but I couldn't find any options related to this. Am I missing anything?

**Comment by eagr** [comment]
https://github.com/awslabs/duvet/blob/main/www/src/result.js#L60

Seems related to this field.

**Comment by camshaft** [comment]
Yes the js needs to be updated to add the section prefix. But the tool does still recognize the shortened id.
