### ISSUE TITLE
False match

### ISSUE THREAD

**Issue by eagr** [awslabs/duvet#70]
Spec:
```
INADEQUATE_SECURITY (0x0c):  Not applicable, since QUIC is assumed to
   provide sufficient security on all connections.

HTTP_1_1_REQUIRED (0x0d):  H3_VERSION_FALLBACK in Section 8.1.

Error codes need to be defined for HTTP/2 and HTTP/3 separately.  See
Section 11.2.3.
```

Extracted requirement:
```
[[spec]]
level = "MUST"
quote = '''
HTTP_1_1_REQUIRED (0x0d):  H3_VERSION_FALLBACK in Section 8.1.
'''
```

Might need to add some word bound assertions?

**Comment by camshaft** [comment]
It seems to be keying off of the REQUIRED part. So we'll need to have some checks on both sides of the keyword to make sure it stands on its own.

**Comment by eagr** [comment]
```rs
    static ref KEY_WORDS: Vec<(Regex, AnnotationLevel)> = {
        let matches = [
            ("(?:MUST NOT|MUST)", AnnotationLevel::Must),
            ("(?:SHALL NOT|SHALL)", AnnotationLevel::Must),
            ("REQUIRED", AnnotationLevel::Must),
            ("(?:SHOULD NOT|SHOULD)", AnnotationLevel::Should),
            ("(?:NOT RECOMMENDED|RECOMMENDED)", AnnotationLevel::Should),
            ("MAY", AnnotationLevel::May),
            ("OPTIONAL", AnnotationLevel::May),
        ];

        matches
            .iter()
            .cloned()
            .map(|(pat, l)| {
                let r = Regex::new(&format!("\\b{}\\b\"?", pat))?;
                Ok((r, l))
            })
            .collect::<Result<_, Error>>()
            .unwrap()
    };
```

Does this seem right to you?

**Comment by camshaft** [comment]
I think this will have issues with the following example sentence:

> In order to be compliant, feature A is REQUIRED.

or 

> Feature B is OPTIONAL.

I'm trying to think of an example where you'd have a non-space before the keywords, though.

**Comment by eagr** [comment]
<img width="583" alt="image" src="https://user-images.githubusercontent.com/64203473/187815549-2715545e-c36e-4725-b103-0fe619bce0f7.png">

**Comment by camshaft** [comment]
Ah nice! Do we know if rust's regex crate supports that?

**Comment by eagr** [comment]
Yes, it does. I could build duvet locally with the change and the extraction result looks good. I'll send a pr for that.
