### ISSUE TITLE
Annotation placed at the end of a source file is ignored

### ISSUE THREAD

**Issue by eagr** [awslabs/duvet#73]
regardless of annotation type

**Comment by camshaft** [comment]
Can you give a specific example of what's happening? I just want to make sure it's clear what exactly is happening.

**Comment by eagr** [comment]
I changed the title to better state the problem.

This may help reproduce the problem:
* copy a requirement from the report that hasn't been annotated
* paste it to the end of any source file that is to be scanned
* run `duvet report` and check the report

The annotation seems to be ignored, as if it weren't in the source code, regardless of annotation type.

Then I try putting something after that annotation, say a dummy comment, and run `duvet report` again. It becomes effective and is reflected in the report.

**Comment by camshaft** [comment]
The bug here is we don't finalize the state machine after completing the last line.

https://github.com/awslabs/duvet/blob/02c92452158debf1be82c702824689ab01b08aa0/src/pattern.rs#L98

I can push a fix
