### ISSUE TITLE
Stat not adding up

### ISSUE THREAD

**Issue by eagr** [awslabs/duvet#80]
<img width="716" alt="image" src="https://user-images.githubusercontent.com/64203473/189169893-9b1a4998-6435-40e7-bfbb-4c558e03dae2.png">

The *Complete* stat of the MUST level is one off somehow. Not sure how though.

**Comment by camshaft** [comment]
https://github.com/awslabs/duvet/blob/17e1d6509a048bc91032a94849505381c890c118/www/src/result.js#L51-L53

If I had to guess, I think you have 14 implications, 14 tests (with one missing a citation), and 36 exceptions.

But this does highlight a need to give better insight into these numbers in the report.

**Comment by eagr** [comment]
> I think you have 14 implications, 14 tests (with one missing a citation), and 36 exceptions.

That's exactly the case. Found the requirement that's missing a citation.

As someone who's trying to generate the report, I'd love to see some `Unknown` stat. But it becomes noise immediately after we finish annotating the code. Maybe consider turning the Stats table into a `DataGrid` which supports hiding columns by choice if it turns out that there are many more desirable stats?
